version: "3"
services:
  app:
    image: ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/${REPO_NAME}:${IMG_TAG}
    build: .
    environment:
      BG_COLOR: ${BG_COLOR}
    command: ["sh", "-c", "
      envsubst </usr/share/nginx/html/index.html.in >/usr/share/nginx/html/index.html &&
      nginx -g 'daemon off;'"]
    logging:
      driver: awslogs
      options:
        awslogs-group: /sample/app
        awslogs-region: ap-northeast-1
        awslogs-stream-prefix: app
    ports:
      - "80:80"
